[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = "./qemu.sh"
rustflags = [
    "-C", "target-cpu=cortex-a53",
    "-C", "link-arg=--script=.cargo/layout.ld",
    "-C", "link-arg=--no-dynamic-linker",
]

[profile.release]
debug  = 2   # embed full DWARF (or at least 1)
strip  = "none"